apiVersion: v1
kind: Service
metadata:
  name: my-node-server-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  loadBalancerIP: 34.91.92.62  # Replace with your reserved static IP
  selector:
    app: my-node-server
  ports:
    - protocol: TCP
      port: 8080    # External port
      targetPort: 8080  # Port inside the pod
